In [2]:
#concat hourly data csv files 
import json
import pandas as pd
from pandas import np
a=['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']
for l in range(0,15):
    for y in range(2013,2018):
        year=str(y)
        file1=pd.read_csv(r'C:\Users\Marjerie\Desktop\hourly data\ '.rstrip()+year+'-'+a[l]+'-hourly-1.csv')
        file2=pd.read_csv(r'C:\Users\Marjerie\Desktop\hourly data\ '.rstrip()+year+'-'+a[l]+'-hourly-2.csv')
        new=pd.concat([file1,file2])
        for i in range(3,13):
            no=str(i)
            file = pd.read_csv(r'C:\Users\Marjerie\Desktop\hourly data\ '.rstrip()+year+'-'+a[l]+'-hourly-'+no+'.csv')
            new=pd.concat([new,file])
        new.to_csv(year+'-'+a[l]+'-hourly.csv',index=False,encoding='utf-8')

In [3]:
#delete unwanted airport information #df.isin
import pandas as pd
a=['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']
for y in range(2013,2018):
    for k in range(1,13):
        year=str(y)
        no=str(k)
        df=pd.read_csv(r'C:\Users\Marjerie\Desktop\FD\On_Time_On_Time_Performance_'+year+'_'+no+'.csv',low_memory=False)
        df1=df[((df.Origin =='ATL')|(df.Origin =='CLT')|(df.Origin =='DEN')|(df.Origin =='DFW')|(df.Origin =='EWR')|(df.Origin =='IAH')|(df.Origin =='JFK')|(df.Origin =='LAS')|(df.Origin =='LAX')|(df.Origin =='MCO')|(df.Origin =='MIA')|(df.Origin =='ORD')|(df.Origin =='PHX')|(df.Origin =='SEA')|(df.Origin =='SFO'))& ((df.Dest =='ATL')|(df.Dest =='CLT')|(df.Dest =='DEN')|(df.Dest =='DFW')|(df.Dest =='EWR')|(df.Dest =='IAH')|(df.Dest =='JFK')|(df.Dest =='LAS')|(df.Dest =='LAX')|(df.Dest =='MCO')|(df.Dest =='MIA')|(df.Dest =='ORD')|(df.Dest =='PHX')|(df.Dest =='SEA')|(df.Dest =='SFO'))]
        df1.to_csv(year+'-flight-'+no+'.csv',index=False,encoding='utf-8')
        del df
        del df1

In [2]:
#drop unwanted columns from flight data
import pandas as pd
for num in range(1,13):
    for y in range(2013,2018):
        year=str(y)
        no=str(num)
        df1=pd.read_csv(r'C:\Users\Marjerie\Desktop\FD1\ '.rstrip()+year+'-flight-'+no+'.csv',low_memory=False)
        df2=df1[['FlightDate','Quarter','Year','Month','DayofMonth','DepTime','DepDel15','CRSDepTime','DepDelayMinutes','Origin','Dest','ArrTime','CRSArrTime','ArrDel15','ArrDelayMinutes']].copy()
        df2.to_csv(year+'-flight-'+no+'.csv',index=False,encoding='utf-8')
        del df1
        del df2

In [3]:
#drop unwanted columns from weather data
import pandas as pd
from pandas import np
a=['ATL','CLT','DEN','DFW','EWR','IAH','JFK','LAS','LAX','MCO','MIA','ORD','PHX','SEA','SFO']
for l in range(0,15):
    for y in range(2013,2018):
        year=str(y)
        df1=pd.read_csv(r'C:\Users\Marjerie\Desktop\hourly concat data\ '.rstrip()+ year+'-'+a[l]+'-hourly.csv',low_memory=False)
        df2=df1[['date','time','tempF','windspeedKmph','winddirDegree','weatherCode','precipMM','humidity','visibility','pressure','cloudcover','DewPointF','WindChillF','WindGustKmph']].copy()
        df2['airport'] = a[l]
        df2.to_csv(year+'-weather-'+a[l]+'.csv',index=False,encoding='utf-8')
        del df1
        del df2

In [4]:
#concat yearly flight data
for y in range(2013,2018):
    year=str(y)
    new=pd.read_csv(r'C:\Users\Marjerie\Desktop\FD2\ '.rstrip()+year+'-flight-1.csv',low_memory=False)
    for i in range(2,13):
        no=str(i)
        file=pd.read_csv(r'C:\Users\Marjerie\Desktop\FD2\ '.rstrip()+year+'-flight-'+no+'.csv',low_memory=False)
        new=pd.concat([new,file])
    new.to_csv(year+'-flight.csv',index=False,encoding='utf-8')
    del new

In [5]:
#concat yearly weather data
for y in range(2013,2018):
    year=str(y)
    new=pd.read_csv(r'C:\Users\Marjerie\Desktop\W1\ '.rstrip()+year+'-weather-ATL.csv',low_memory=False)
    for i in range(1,15):
        file=pd.read_csv(r'C:\Users\Marjerie\Desktop\W1\ '.rstrip()+year+'-weather-'+a[i]+'.csv',low_memory=False)
        new=pd.concat([new,file])
    new.to_csv(year+'-weather.csv',index=False,encoding='utf-8')

In [6]:
for y in range(2013,2018):
    year=str(y)
    df=pd.read_csv(r'C:\Users\Marjerie\Desktop\FD3\ '.rstrip()+year+ '-flight.csv',low_memory=False)
    df=df.dropna()
    df['time']=((df['DepTime']/100).astype(int))*100
    df['airport'] = df['Origin']
    vals={'ATL' : 1, 'CLT' : 2, 'DEN' : 3, 'DFW' : 4, 'EWR' : 5, 'IAH' : 6, 'JFK' : 7, 'LAS' : 8, 'LAX' : 9, 'MCO' : 10, 'MIA' : 11, 'ORD' : 12, 'PHX' : 13, 'SEA' : 14, 'SFO' : 15}
    df = df.replace({'Origin' : vals}) 
    df.to_csv(year+'-flight.csv',index=False,encoding='utf-8')
    del df

In [7]:
#merge on the basis of time and date
for y in range(2013,2018):
    year=str(y)
    df1=pd.read_csv(r'C:\Users\Marjerie\Desktop\W2\ '.rstrip()+year+ '-weather.csv',low_memory=False)
    df=pd.read_csv(r'C:\Users\Marjerie\Desktop\FD4\ '.rstrip()+year+ '-flight.csv',low_memory=False)
    df = df.rename(columns={'FlightDate': 'date'})
    new_df=df.merge(df1,on=['date','time','airport'])
    new_df.to_csv(year+'-merged.csv',index=False,encoding='utf-8')
    del df
    del df1 
    del new_df

In [4]:
new=pd.read_csv(r'C:\Users\Marjerie\Desktop\M2\2013-merged1.csv',low_memory=False)
for y in range(2014,2016):
    year=str(y)
    file=pd.read_csv(r'C:\Users\Marjerie\Desktop\M2\ '.rstrip()+year+'-merged1.csv',low_memory=False)
    new=pd.concat([new,file])
new.to_csv('train.csv',index=False,encoding='utf-8')
del new

In [8]:
for y in range(2013,2018):
    year=str(y)
    df=pd.read_csv(r'C:\Users\Marjerie\Desktop\M1\ '.rstrip()+year+ '-merged.csv',low_memory=False)
    df1=pd.read_csv(r'C:\Users\Marjerie\Desktop\W2\ '.rstrip()+year+ '-weather.csv',low_memory=False)
    df1=df1.add_suffix('_d')
    df1 = df1.rename(columns={'airport_d': 'Dest','time_d':'time','date_d':'date'})
    new_df=df.merge(df1,on=['date','time','Dest'])
    new_df.to_csv(year+'-merged1.csv',index=False,encoding='utf-8')
    del df
    del df1
    del new_df

In [1]:
import numpy as np
import pandas as pd
df= pd.read_csv(r'C:\Users\Marjerie\Desktop\train.csv')
vals={'ATL' : 1, 'CLT' : 2, 'DEN' : 3, 'DFW' : 4, 'EWR' : 5, 'IAH' : 6, 'JFK' : 7, 'LAS' : 8, 'LAX' : 9, 'MCO' : 10, 'MIA' : 11, 'ORD' : 12, 'PHX' : 13, 'SEA' : 14, 'SFO' : 15}
df = df.replace({'Dest' : vals}) 
df1=df.drop(['date','time','Year','airport','DepDel15','CRSDepTime','CRSArrTime','ArrDel15','ArrDelayMinutes'], axis=1)
df2=df['ArrDel15']
X= df1.values
y= df2.values
X = X.astype(int)
y = y.astype(int)
df= pd.read_csv(r'C:\Users\Marjerie\Desktop\test.csv')
vals={'ATL' : 1, 'CLT' : 2, 'DEN' : 3, 'DFW' : 4, 'EWR' : 5, 'IAH' : 6, 'JFK' : 7, 'LAS' : 8, 'LAX' : 9, 'MCO' : 10, 'MIA' : 11, 'ORD' : 12, 'PHX' : 13, 'SEA' : 14, 'SFO' : 15}
df = df.replace({'Dest' : vals}) 
df3=df.drop(['date','time','airport','Year','DepDel15','CRSDepTime','CRSArrTime','ArrDel15','ArrDelayMinutes'], axis=1)
df4=df['ArrDel15']
X_test= df3.values
y_test= df4.values
X_test = X_test.astype(int)
y_test = y_test.astype(int)

In [20]:
import imblearn
from imblearn.over_sampling import SMOTE 
sm = SMOTE()
X_rtrain, y_rtrain = sm.fit_sample(X, y)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import sklearn as sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
model = RandomForestClassifier(criterion='gini')
model.fit(X_rtrain, y_rtrain)
score=model.score(X_rtrain,y_rtrain)
print (score)
predicted= model.predict(X_test)
print(confusion_matrix(y_test,predicted))  
print(classification_report(y_test,predicted))  
print(accuracy_score(y_test,predicted)) 
print(model.feature_importances_)

0.9950179374034779
[[694844  23981]
 [ 58304 137186]]
             precision    recall  f1-score   support

          0       0.92      0.97      0.94    718825
          1       0.85      0.70      0.77    195490

avg / total       0.91      0.91      0.91    914315

0.9100036639451392
[0.03597055 0.02820142 0.01245523 0.02888879 0.55573238 0.01368114
 0.01117118 0.02333651 0.01147026 0.01738235 0.0122775  0.00948768
 0.01397588 0.01094375 0.0081209  0.01190801 0.01633246 0.01074657
 0.01097797 0.01104278 0.01025178 0.0179306  0.01192505 0.01021049
 0.0117426  0.01084894 0.01086234 0.01102294 0.0190144  0.01059467
 0.01005739 0.01143553]


In [6]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import sklearn as sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
model = RandomForestClassifier(criterion='gini')
model.fit(X, y)
score=model.score(X,y)
print (score)
predicted= model.predict(X_test)
print(confusion_matrix(y_test,predicted))  
print(classification_report(y_test,predicted))  
print(accuracy_score(y_test,predicted)) 
print(model.feature_importances_)

0.990403875991621
[[702294  16531]
 [ 63607 131883]]
             precision    recall  f1-score   support

          0       0.92      0.98      0.95    718825
          1       0.89      0.67      0.77    195490

avg / total       0.91      0.91      0.91    914315

0.9123518699791647
[0.00341561 0.00839046 0.01466145 0.04058074 0.54550741 0.0112714
 0.01090127 0.04339526 0.01623776 0.01484511 0.02081957 0.00714946
 0.00419814 0.0173189  0.00446338 0.01507808 0.01516683 0.01623228
 0.01714728 0.01525749 0.01547878 0.01484595 0.02013719 0.00699369
 0.00290015 0.01731181 0.00445402 0.01454693 0.01470728 0.01603075
 0.01562238 0.0149332 ]


In [7]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import sklearn as sklearn
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import tree
model = GradientBoostingClassifier()
model.fit(X, y)
score=model.score(X,y)
print (score)
predicted= model.predict(X_test)
print(confusion_matrix(y_test,predicted))  
print(classification_report(y_test,predicted))  
print(accuracy_score(y_test,predicted)) 
print(model.feature_importances_)

0.9131959083634821
[[701543  17282]
 [ 60270 135220]]
             precision    recall  f1-score   support

          0       0.92      0.98      0.95    718825
          1       0.89      0.69      0.78    195490

avg / total       0.91      0.92      0.91    914315

0.9151802168836779
[0.0016773  0.00862259 0.00092217 0.05079427 0.39363246 0.05404125
 0.04701708 0.12074974 0.02408183 0.00921216 0.00962315 0.02670175
 0.00991755 0.00094735 0.01308116 0.02485369 0.00197577 0.00182013
 0.04284232 0.00222038 0.00731218 0.01260238 0.01789435 0.01246147
 0.00816903 0.01488951 0.01397521 0.01396345 0.02131524 0.01582158
 0.00471724 0.01214426]


In [8]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import sklearn as sklearn
from sklearn.ensemble import ExtraTreesClassifier
from sklearn import tree
model = ExtraTreesClassifier()
model.fit(X, y)
score=model.score(X,y)
print (score)
predicted= model.predict(X_test)
print(confusion_matrix(y_test,predicted))  
print(classification_report(y_test,predicted))  
print(accuracy_score(y_test,predicted)) 
print(model.feature_importances_)

KeyboardInterrupt: 

In [3]:
df1.shape

(2706301, 32)

In [4]:
df2.shape

(2706301,)

In [5]:
df3.shape

(914315, 32)

In [6]:
df4.shape

(914315,)